name: Set up Node
description: Set up Node and npm
inputs:
  cwd:
    description: Working directory
    required: false
    default: "./frontend"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: latest
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
        cache-dependency-path: "${{ inputs.cwd }}/pnpm-lock.yaml"

    - name: Install dependencies
      run: pnpm install
      working-directory: ${{ inputs.cwd }}
      shell: bash
