name: Build

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true

  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and deploy
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tira-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            MODE=${{ vars.MODE }}
