on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
    inputs:
      working-directory:
        type: string
        default: .

jobs:
  Unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: game-ai-platform-team/workflows/.github/workflows/setup-node@main

      - name: Run unit tests
        run: pnpm run coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage/coverage-final.json

  Format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: game-ai-platform-team/workflows/.github/workflows/setup-node@main

      - name: Format code
        run: pnpm run format

      - name: Fix lint issues
        run: pnpm run lint:fix

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "style: Format code"
          pull: "--rebase --autostash"

  Lint:
    runs-on: ubuntu-latest
    needs: Format
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: game-ai-platform-team/workflows/.github/workflows/setup-node@main

      - name: Run lint
        run: pnpm run lint
