name: CI (Node)

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

defaults:
  run:
    working-directory: .

jobs:
  Unit_test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/workflows/setup-node

      - name: Run unit tests
        run: pnpm run coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: game-ai-platform-team/tira-ai-platform
        with:
          files: ./coverage/coverage-final.json

  Format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/workflows/setup-node

      - name: Format code
        run: pnpm run format

      - name: Fix lint issues
        run: pnpm run lint:fix

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "style: Format code"
          pull: "--rebase --autostash"

  Lint:
    runs-on: ubuntu-latest
    needs: Format

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/workflows/setup-node

      - name: Run lint
        run: pnpm run lint
