on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
      OIDC_CLIENT_ID:
        required: true
      OIDC_CLIENT_SECRET:
        required: true
    inputs:
      environment:
        type: string
        required: true
      working-directory:
        type: string
        default: .

jobs:
  Unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    environment: ${{ inputs.environment }}
    env:
      OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
      OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Poetry
        uses: game-ai-platform-team/setup-poetry@main

      - name: Run unit tests
        run: poetry run invoke coverage-xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage.xml

  Lint:
    runs-on: ubuntu-latest
    needs: Format
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Poetry
        uses: game-ai-platform-team/setup-poetry@main

      - name: Run pylint
        run: poetry run invoke lint

  Format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Poetry
        uses: game-ai-platform-team/setup-poetry@main

      - name: Format code
        run: poetry run invoke format

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "style: Format code"
          pull: "--rebase --autostash"
