name: End-to-end testing

on:
  workflow_call:
    secrets:
      OIDC_CLIENT_ID:
        required: true
      OIDC_CLIENT_SECRET:
        required: true

jobs:
  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest
    environment: staging
    env:
      NODE_ENV: development
      OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
      OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Poetry
        uses: ./.github/workflows/setup-poetry

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          wait-on: "http://localhost:5000"
          wait-on-timeout: 10
          build: pnpm run build
          start: pnpm run server
